### ISSUE TITLE
Structure of the NEWS.md file

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/ww-inference-model#118]
> Got it! That said, I think the NEWS.md file is improperly structured. I will put it on the bottom and then make an issue pointing this out (R CMD check highlights this).

_Originally posted by @gvegayon in https://github.com/CDCgov/ww-inference-model/pull/58#discussion_r1734916434_

**Comment by gvegayon** [comment]
For your reference, R provides some information about the structure of `NEWS.md` files here: https://stat.ethz.ch/R-manual/R-devel/library/utils/html/news.html

**Comment by kaitejohnson** [comment]
I can take a pass at formatting this way and have you review! [slurmR/NEWS.md at master · USCbiostats/slurmR (github.com)](https://github.com/USCbiostats/slurmR/blob/master/NEWS.md) 

Since we don't have an official release yet, I think I will have to start with describing the components at a high level, which will include references to the PRs currently in the `NEWS.md`
