### ISSUE TITLE
 Fix `check_req_ww_cols_present`

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#98]
## Problem
The function did not work as expected. The error message was non-intuitive when 'site' was missing. It failed BEFORE it got to the checker message.

## Requirements
- [ ] fix `check_req_ww_cols_present`
- [ ] add a test to replicate and see what happens when `site` was missing

## Context
- user feedback when running with own data

**Comment by dylanhmorris** [comment]
I think at least one issue here is that regex pattern (which I wrote; my apologies) for `autoescape_brackets()` isn't quite right.

```R
autoescape_brackets <- function (string)
{
    return(gsub("\\{(.*)\\}", "{{\\1}}", string))
}
```
The clue is in the error message that @kaitejohnson got. Note the trailing bracket.
```R
Names must include the elements {'log_genome_copies_per_ml','lod','date','site','lab','site_pop'}, but is
missing elements site}
```

The problem is that `checkmate::check_names()` messages are of the form:

```R
Names must include the elements {'a', 'b', 'c'}, but is
missing elements {'a', 'b'}
```

```R
gsub("\\{(.*)\\}", "{{\\1}}", "{a}, {b}")
```
yields: 

```R
[1] "{{a}, {b}}"
```

This is because as written the pattern matches and replaces the _outermost_ brackets, not pairs of brackets reading left to right.

On reflection, I'm not sure the brackets are needed in the error message. We could just get rid of them (`gsub("\\{|\\}", "", string)`:

```R
Names must include the elements 'log_genome_copies_per_ml','lod','date','site','lab','site_pop', but is
missing elements 'site'
```

But if we do want the brackets, the simplest solution is probably sequential `gsub`: `gsub(,"\\}", "}}, gsub("\\{", "{{", string))`.

**Comment by kaitejohnson** [comment]
I think I'm in favor of getting rid of all of the brackets! I will rewrite the `autoescape_brackets()` function! Thanks for the debugging @dylanhmorris I missed that checkmates returns two things of brackets!

**Comment by gvegayon** [comment]
I think this would also work:

```r
> gsub("\\{([^}]+,?)\\}", "{{\\1}}", "{a}, {b}") 
```

Yields

```r
[1] "{{a}}, {{b}}"
```

And

```r
gsub("\\{([^}]+,?)\\}", "{{\\1}}", "{a,b}, {b}") 
```

yields

```r
[1] "{{a,b}}, {{b}}"
```

**Comment by kaitejohnson** [comment]
@gvegayon I guess I would just rather not have brackets though?
